version: '3'
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET=your-secret-key
      - DB_URI=mongodb://mongo:27017/zetachat
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
